steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/speedtest:dev', '.']

# Simple unit test: invoke the new gcloud container to confirm that it was
# built correctly.
# - name: 'gcr.io/$REPO_NAME/gcloud'
#   args: ['info']

# Invoke a command that requires auth, to check that it gets piped through
# correctly.
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['source', 'repos', 'clone', 'speedtest']

images: ['gcr.io/$PROJECT_ID/speedtest:dev']